### PR TITLE
Textarea needs inputRef similar to Input so we can focus onComponentD…

### PR DESCRIPTION
**Pull request by jrhicks**
…idMount and similar.

### CODE REVIEW

**Comment by stomita** [comment]
`textareaRef` might be better rather than `inputRef` as the pointing DOM element is `<textarea>`.
@ButuzGOL how do you think ?

**Comment by ButuzGOL** [comment]
yes sure

**Comment by jrhicks** [comment]
I updated the commit to use textareaRef

**Comment by ButuzGOL** [comment]
please merge master so we will merge pr

**Comment by jrhicks** [comment]
Merge master complete (I think)

**Pull request merged**
