### PR TITLE
Set SvgIcon href without __dangerouslySetInnerHtml

### PR DESCRIPTION
**Pull request by bondz**
React 15.x now supports the xlink:href SVG attribute (as xlinkHref)

### CODE REVIEW

**Comment by ButuzGOL** [comment]
plz check ci

**Comment by stomita** [comment]
Targeting only React 15.x is not what I want to do in master branch now - living project might still be using 14.x or earlier.

**Comment by bondz** [comment]
@stomita looks like it works in `react@0.14` see http://www.webpackbin.com/N15JqgdKG

**Comment by ButuzGOL** [comment]
I think its ok to merge if 14 works with svg @stomita  ?

**Pull request merged**
