### PR TITLE
Lookup enhancements and small fixes

### PR DESCRIPTION
**Pull request by snownoop**
main changes:
1) Added babel-plugin-transform-class-properties to package.json for .babelrc
2) Add renderer function for pill
3) Fix toggle click function of TreeNode
4) Add renderer for TreeNode

Lookup changes:
1) Tree Structure support
2) Tree Structure splitter support
3) Add renderes for Lookup candidate list and Lookup selection
4) Add nested filter function to filter Tree-structured data
5) Add lookup wrapper block styles property
6) Add allowEmpty property
7) Add noDataLabel property if no data was specified
8) Use object value for selected prop, not object itself

### CODE REVIEW

**Comment by snownoop** [comment]
@stomita  @ButuzGOL  please review lookup fixes and features commit. Thanks.

**Comment by stomita** [comment]
@snownoop What is the purpose of adding tree data lookup ? I don't think the Lookup component should deliver this feature. Adding many features to one component may bring corruption to the current behavior (actually, the Lookup Examples are not working as before in your branch). You can create the component by your own.

**Comment by ButuzGOL** [comment]
but @stomita if we need this tree structure in lookup how should we handle it ?

**Comment by stomita** [comment]
@ButuzGOL It is not the special for Lookup component. Sometime your app may need an extension to an existing component. Currently Lookup doesn't have the extension point, although it would be better to have it in proper way. Adding support for tree rendering especially is not the right way.

**Comment by ButuzGOL** [comment]
please check description i think its quite good to have such functionality in lookup and it hasnt conflict with slds framework ?

**Comment by snownoop** [comment]
@stomita I also think that as long as it is not ruining other functional, extension-functionality like tree structure, etc should be good for component. You can check examples and code to be sure it is working fine. We are not removing any existing functional or breaking something. Thanks.

**Comment by ButuzGOL** [comment]
@stomita if you think changes to big to understand lets break into several chunks ?

**Comment by stomita** [comment]
> We are not removing any existing functional or breaking something

Please check the examples of Lookup. Your branch is showing the corruption.

localhost_3000___lookup

Correct in master branch

localhost_3000___lookup

**Pull request closed without merging**
