### PR TITLE
Table component

### PR DESCRIPTION
**Pull request by snownoop**
changes:

1) New Table component
2) Remove of PageHeader wrapper

### CODE REVIEW

**Comment by snownoop** [comment]
@stomita  @ButuzGOL  please take a look. Thanks.

**Comment by ButuzGOL** [comment]
Looks good Please check ci

**Comment by snownoop** [comment]
@stomita @ButuzGOL i fixed linter.

**Comment by stomita** [comment]
@snownoop `offset()` function in `util.js` is not used, right ?

**Pull request merged**
